# Generated by Django 5.1.1 on 2024-09-15 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('is_vendor', models.BooleanField(blank=True, default=False, null=True)),
                ('is_premium', models.BooleanField(blank=True, default=False, null=True)),
                ('in_process', models.BooleanField(blank=True, default=False, null=True)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPremiumAppplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number1', models.CharField(max_length=11, null=True)),
                ('phone_number2', models.CharField(max_length=11, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(blank=True, default='What is your username', max_length=255)),
                ('answer1', models.CharField(blank=True, default='', max_length=255)),
                ('question2', models.CharField(blank=True, default='What is your favourite colour?', max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('username', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Kastina', 'Kastina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara'), ('FCT (Abuja)', 'FCT (Abuja)')], max_length=100, null=True)),
                ('location', models.TextField(null=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('business_logo_if_any', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('vendor_phone_number1', models.IntegerField(null=True)),
                ('vendor_phone_number2', models.IntegerField(blank=True, null=True)),
                ('business_whatsapp_number', models.CharField(max_length=500, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=500)),
                ('X_or_twitter_username', models.CharField(blank=True, max_length=500, null=True)),
                ('fashion_vendor', models.BooleanField(blank=True, default=False)),
                ('food_vendor', models.BooleanField(blank=True, default=False)),
                ('supermarket_vendor', models.BooleanField(blank=True, default=False)),
                ('electronics_vendor', models.BooleanField(blank=True, default=False)),
                ('services_vendor', models.BooleanField(blank=True, default=False)),
                ('blog_vendor', models.BooleanField(blank=True, default=False)),
                ('is_premium', models.BooleanField(blank=True, default=False)),
                ('premium_1', models.BooleanField(blank=True, default=False)),
                ('premium_2', models.BooleanField(blank=True, default=False)),
                ('premium_3', models.BooleanField(blank=True, default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('vendor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Premium3Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type1', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_type2', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_type3', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_type4', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_type5', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_name', models.CharField(max_length=50)),
                ('phone_number1', models.IntegerField()),
                ('phone_number2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business_WhatsApp_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Premium2Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type1', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_type2', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_type3', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_name', models.CharField(max_length=50)),
                ('phone_number1', models.IntegerField()),
                ('phone_number2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business_WhatsApp_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Premium1Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type1', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_type2', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_name', models.CharField(max_length=50)),
                ('phone_number1', models.IntegerField()),
                ('phone_number2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business_WhatsApp_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('Fashion', 'Fashion'), ('Food', 'Food'), ('Supermarket', 'Supermarket'), ('Electronics', 'Electronics'), ('Services', 'Services')], max_length=100, null=True)),
                ('business_name', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Kastina', 'Kastina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara'), ('FCT (Abuja)', 'FCT (Abuja)')], max_length=100, null=True)),
                ('location', models.TextField(null=True)),
                ('phone_number1', models.IntegerField()),
                ('phone_number2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business_WhatsApp_number', models.IntegerField()),
                ('how_did_you_here_about_us', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Instagram', 'Instagram'), ('X or Twitter', 'X or Twitter'), ('Someone', 'Someone'), ('Other', 'Other')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='images/')),
                ('Means_of_Identification', models.CharField(choices=[('NIN', 'NIN'), ("Driver's Lincense", "Driver's Lincense"), ('Student_ID', 'Student_ID'), ("Voter's Card", "Voter's Card")], max_length=100, null=True)),
                ('front_view', models.ImageField(null=True, upload_to='images/')),
                ('back_view', models.ImageField(null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
