from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views


urlpatterns = [
    # path('', home, name = 'home'),
    # path('signup/', signupPage, name='signup'),
    # path('login/', loginPage, name='login'),
    # path('logout/', logoutUser, name='logout'),
    # # path('edit_profile/<str:data>/', editCustomerProfile, name= "edit_customer_profile"),
    # path('customer/', customerBase, name='customer'),
    # path('customer_profile/', customerProfile, name='customer_profile'),
    # path('update/<update>', fashionProduct, name='update'),
    # path('categories/', categories, name='categories'),
    # path('fashion_categories/', fashionCategory, name='fashion_category'),
    # path('fashion/<fash_pro>', fashionProduct, name='fashion'),
    # path('get_fashion/<str:pk>', getFashion, name='get_fashion'),
    # path('create_product/', createProduct, name='create_product'),
    # path('food/', food, name='food'),
    # path('blogs/', blogs, name='blog'),
    # path('get_blogs/<str:pk>', getBlog, name='get_blog'),
    # path('get_food/<int:pk>/', getFood, name='get_food'),
    # path('supermarket/', supermarket, name='supermarket'),
    # path('get_supermarket/<int:pk>/', getSupermarket, name='get_supermarket'),
    # path('service/', service, name='service'),
    # path('get_service/<int:pk>/', getService, name='get_service'),
    # path('crypto/', crypto, name='crypto'),
    # path('get_crypto/<int:pk>/', getCrypto, name='get_crypto'),
    # path('electronic/', electronic, name='electronic'),
    # path('get_electronic/<int:pk>/', getElectronic, name='get_electronic'),
    # path('history/', history, name='history'),
    # path('my_blogs', myBlog, name='my_blog'),
    # path('create_blog', BlogCreateView.as_view(), name='create_blog'),
    # path('update_product/<int:pk>/', updateProduct, name='update_product'),
    # path('delete_product/<int:pk>/', deleteProduct, name='delete_product'),
    # path('vendor_profile', vendorProfile, name='vendor_profile'),
    # path('vendor', vendor, name='vendor'),
    # path('vendor_application', vendorApplication, name='vendor_application'),
    # path('vendor_detail/<int:pk>/', vendorDetail, name='vendor_detail'),
    # path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    # path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_comfirm'),
    # path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    ]
