# Generated by Django 5.1.1 on 2024-09-15 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('discription', models.TextField(blank=True, null=True)),
                ('crypto_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
        ),
    ]
