# Generated by Django 5.1.1 on 2024-09-15 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30, null=True)),
                ('text', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('business_whatsapp_number', models.CharField(max_length=100, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blog_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blog_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blog_image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blog_image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BlogVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30, null=True)),
                ('text', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('business_whatsapp_number', models.CharField(max_length=100, null=True)),
                ('blog_video', models.FileField(null=True, upload_to='videos/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
